"! Shared Audit and Security DTOs and constants.
INTERFACE /fcbp/if_glt_sec_types PUBLIC.

  CONSTANTS:
    BEGIN OF c_action,
      display              TYPE char30 VALUE 'DISPLAY',
      drilldown_package    TYPE char30 VALUE 'DRILLDOWN_PACKAGE',
      drilldown_technical  TYPE char30 VALUE 'DRILLDOWN_TECHNICAL',
      audit_read           TYPE char30 VALUE 'AUDIT_READ',
      retry                TYPE char30 VALUE 'RETRY',
      rebuild              TYPE char30 VALUE 'REBUILD',
      reprocess            TYPE char30 VALUE 'REPROCESS',
      cancel               TYPE char30 VALUE 'CANCEL',
      status_query         TYPE char30 VALUE 'STATUS_QUERY',
      config_view          TYPE char30 VALUE 'CONFIG_VIEW',
      config_change        TYPE char30 VALUE 'CONFIG_CHANGE',
      config_activate      TYPE char30 VALUE 'CONFIG_ACTIVATE',
      support_access       TYPE char30 VALUE 'SUPPORT_ACCESS',
      job_execute          TYPE char30 VALUE 'JOB_EXECUTE',
      retention_execute    TYPE char30 VALUE 'RETENTION_EXECUTE',
    END OF c_action.

  CONSTANTS:
    BEGIN OF c_event_category,
      lifecycle  TYPE char30 VALUE 'LIFECYCLE',
      package    TYPE char30 VALUE 'PACKAGE',
      validation TYPE char30 VALUE 'VALIDATION',
      mapping    TYPE char30 VALUE 'MAPPING',
      adapter    TYPE char30 VALUE 'ADAPTER',
      retry      TYPE char30 VALUE 'RETRY',
      operator   TYPE char30 VALUE 'OPERATOR',
      config     TYPE char30 VALUE 'CONFIG',
      security   TYPE char30 VALUE 'SECURITY',
      support    TYPE char30 VALUE 'SUPPORT',
      job        TYPE char30 VALUE 'JOB',
    END OF c_event_category.

  CONSTANTS:
    BEGIN OF c_event_type,
      receive                  TYPE char30 VALUE 'RECEIVE',
      transfer_registered      TYPE char30 VALUE 'TRANSFER_REGISTERED',
      duplicate_handoff        TYPE char30 VALUE 'DUPLICATE_HANDOFF',
      status_changed           TYPE char30 VALUE 'STATUS_CHANGED',
      posted                   TYPE char30 VALUE 'POSTED',
      cancelled                TYPE char30 VALUE 'CANCELLED',
      reversed                 TYPE char30 VALUE 'REVERSED',
      package_created          TYPE char30 VALUE 'PACKAGE_CREATED',
      package_rebuilt          TYPE char30 VALUE 'PACKAGE_REBUILT',
      validation_passed        TYPE char30 VALUE 'VALIDATION_PASSED',
      validation_failed        TYPE char30 VALUE 'VALIDATION_FAILED',
      mapping_completed        TYPE char30 VALUE 'MAPPING_COMPLETED',
      mapping_failed           TYPE char30 VALUE 'MAPPING_FAILED',
      submit_started           TYPE char30 VALUE 'SUBMIT_STARTED',
      submit_accepted          TYPE char30 VALUE 'SUBMIT_ACCEPTED',
      submit_failed            TYPE char30 VALUE 'SUBMIT_FAILED',
      submit_unknown           TYPE char30 VALUE 'SUBMIT_UNKNOWN',
      status_query_started     TYPE char30 VALUE 'STATUS_QUERY_STARTED',
      status_query_completed   TYPE char30 VALUE 'STATUS_QUERY_COMPLETED',
      retry_scheduled          TYPE char30 VALUE 'RETRY_SCHEDULED',
      retry_exhausted          TYPE char30 VALUE 'RETRY_EXHAUSTED',
      confirmation_pending     TYPE char30 VALUE 'CONFIRMATION_PENDING',
      reprocess_requested      TYPE char30 VALUE 'REPROCESS_REQUESTED',
      rebuild_requested        TYPE char30 VALUE 'REBUILD_REQUESTED',
      cancel_requested         TYPE char30 VALUE 'CANCEL_REQUESTED',
      status_query_requested   TYPE char30 VALUE 'STATUS_QUERY_REQUESTED',
      config_changed           TYPE char30 VALUE 'CONFIG_CHANGED',
      config_activated         TYPE char30 VALUE 'CONFIG_ACTIVATED',
      config_deactivated       TYPE char30 VALUE 'CONFIG_DEACTIVATED',
      auth_denied_action       TYPE char30 VALUE 'AUTH_DENIED_ACTION',
      auth_scope_unresolved    TYPE char30 VALUE 'AUTH_SCOPE_UNRESOLVED',
      dcl_denied               TYPE char30 VALUE 'DCL_DENIED',
      support_access_requested TYPE char30 VALUE 'SUPPORT_ACCESS_REQUESTED',
      support_access           TYPE char30 VALUE 'SUPPORT_ACCESS',
      support_access_denied    TYPE char30 VALUE 'SUPPORT_ACCESS_DENIED',
      support_access_ended     TYPE char30 VALUE 'SUPPORT_ACCESS_ENDED',
      job_started              TYPE char30 VALUE 'JOB_STARTED',
      job_completed            TYPE char30 VALUE 'JOB_COMPLETED',
      job_failed               TYPE char30 VALUE 'JOB_FAILED',
      retention_started        TYPE char30 VALUE 'RETENTION_STARTED',
      retention_completed      TYPE char30 VALUE 'RETENTION_COMPLETED',
    END OF c_event_type.

  CONSTANTS:
    BEGIN OF c_decision_outcome,
      allowed    TYPE char30 VALUE 'ALLOWED',
      denied     TYPE char30 VALUE 'DENIED',
      unresolved TYPE char30 VALUE 'UNRESOLVED',
    END OF c_decision_outcome.

  CONSTANTS:
    BEGIN OF c_purpose,
      monitor          TYPE char30 VALUE 'MONITOR',
      operator_action  TYPE char30 VALUE 'OPERATOR_ACTION',
      audit            TYPE char30 VALUE 'AUDIT',
      support          TYPE char30 VALUE 'SUPPORT',
      config_admin     TYPE char30 VALUE 'CONFIG_ADMIN',
      technical_worker TYPE char30 VALUE 'TECHNICAL_WORKER',
      security_admin   TYPE char30 VALUE 'SECURITY_ADMIN',
    END OF c_purpose.

  CONSTANTS:
    BEGIN OF c_redaction_profile,
      summary   TYPE char30 VALUE 'SUMMARY',
      detail    TYPE char30 VALUE 'DETAIL',
      technical TYPE char30 VALUE 'TECHNICAL',
      audit     TYPE char30 VALUE 'AUDIT',
      support   TYPE char30 VALUE 'SUPPORT',
      blocked   TYPE char30 VALUE 'BLOCKED',
    END OF c_redaction_profile.

  CONSTANTS:
    BEGIN OF c_criticality,
      business_critical TYPE char20 VALUE 'BUSINESS_CRITICAL',
      security          TYPE char20 VALUE 'SECURITY',
      diagnostic        TYPE char20 VALUE 'DIAGNOSTIC',
    END OF c_criticality.

  TYPES: BEGIN OF ty_security_context,
           actor_type         TYPE char12,
           actor_id           TYPE char40,
           user_name          TYPE syuname,
           api_client_id      TYPE char40,
           jobrun_id          TYPE /fcbp/if_glt_types=>ty_jobrun_id,
           support_ticket_id  TYPE char40,
           support_session_id TYPE char40,
           reason_code        TYPE char30,
           reason_text        TYPE char220,
           correlation_id     TYPE /fcbp/if_glt_types=>ty_correlation_id,
           request_id         TYPE char64,
           tenant_id          TYPE char20,
           company_code       TYPE char4,
           target_id          TYPE char20,
           purpose            TYPE char30,
           redaction_profile  TYPE char30,
           valid_from         TYPE utclong,
           valid_until        TYPE utclong,
         END OF ty_security_context.

  TYPES: BEGIN OF ty_auth_decision,
           action             TYPE char30,
           transfer_id        TYPE /fcbp/if_glt_types=>ty_transfer_id,
           allowed            TYPE abap_bool,
           decision_outcome   TYPE char30,
           denial_reason      TYPE char80,
           company_code       TYPE char4,
           target_id          TYPE char20,
           role_scope         TYPE char80,
           requires_audit     TYPE abap_bool,
           evidence_ref       TYPE string,
           actor_id           TYPE char40,
           created_at         TYPE utclong,
         END OF ty_auth_decision.
  TYPES tt_auth_decision TYPE STANDARD TABLE OF ty_auth_decision WITH EMPTY KEY.

  TYPES: BEGIN OF ty_support_scope,
           transfer_id        TYPE /fcbp/if_glt_types=>ty_transfer_id,
           company_code       TYPE char4,
           target_id          TYPE char20,
           support_ticket_id  TYPE char40,
           support_session_id TYPE char40,
           reason_code        TYPE char30,
           reason_text        TYPE char220,
           metadata_only      TYPE abap_bool,
           valid_until        TYPE utclong,
         END OF ty_support_scope.

  TYPES: BEGIN OF ty_redaction_request,
           field_name         TYPE char40,
           raw_value          TYPE char255,
           purpose            TYPE char30,
           redaction_profile  TYPE char30,
           sensitive          TYPE abap_bool,
           raw_allowed        TYPE abap_bool,
         END OF ty_redaction_request.

  TYPES: BEGIN OF ty_redaction_result,
           field_name      TYPE char40,
           display_value   TYPE char255,
           redacted        TYPE abap_bool,
           audit_required  TYPE abap_bool,
         END OF ty_redaction_result.

  TYPES: BEGIN OF ty_audit_filter,
           transfer_id        TYPE /fcbp/if_glt_types=>ty_transfer_id,
           event_category     TYPE char30,
           event_type         TYPE char30,
           actor_id           TYPE char40,
           company_code       TYPE char4,
           target_id          TYPE char20,
           support_ticket_id  TYPE char40,
           created_from       TYPE utclong,
           created_to         TYPE utclong,
         END OF ty_audit_filter.

  TYPES: BEGIN OF ty_config_change,
           config_object_type TYPE char30,
           config_object_key  TYPE char80,
           config_version     TYPE char20,
           activity           TYPE char30,
           company_code       TYPE char4,
           target_id          TYPE char20,
           old_value_hash     TYPE char64,
           new_value_hash     TYPE char64,
           reason_code        TYPE char30,
           reason_text        TYPE char220,
           changed_by         TYPE syuname,
         END OF ty_config_change.

ENDINTERFACE.
