"! Job Layer shared vocabulary and DTOs.
"! Source: DTS GL Bridge Job Layer, Sections 4, 5, 6, and 8.
INTERFACE /fcbp/if_glt_job_types PUBLIC.

  CONSTANTS:
    BEGIN OF c_job_type,
      dispatch_due_work    TYPE char30 VALUE 'DISPATCH_DUE_WORK',
      backlog_dispatch     TYPE char30 VALUE 'BACKLOG_DISPATCH',
      retry_due_work       TYPE char30 VALUE 'RETRY_DUE_WORK',
      poll_confirmation    TYPE char30 VALUE 'POLL_CONFIRMATION',
      status_query         TYPE char30 VALUE 'STATUS_QUERY',
      batch_handoff        TYPE char30 VALUE 'BATCH_HANDOFF',
      package_validate     TYPE char30 VALUE 'PACKAGE_VALIDATE',
      package_map          TYPE char30 VALUE 'PACKAGE_MAP',
      package_rebuild      TYPE char30 VALUE 'PACKAGE_REBUILD',
      package_consistency  TYPE char30 VALUE 'PACKAGE_CONSISTENCY',
      adapter_health       TYPE char30 VALUE 'ADAPTER_HEALTH',
      config_health        TYPE char30 VALUE 'CONFIG_HEALTH',
      registration_recovery TYPE char30 VALUE 'REGISTRATION_RECOVERY',
      retention            TYPE char30 VALUE 'RETENTION',
      reconciliation       TYPE char30 VALUE 'RECONCILIATION',
      route_simulation     TYPE char30 VALUE 'ROUTE_SIMULATION',
      policy_context_check TYPE char30 VALUE 'POLICY_CONTEXT_CHECK',
      source_read_probe    TYPE char30 VALUE 'SOURCE_READ_PROBE',
    END OF c_job_type.

  CONSTANTS:
    BEGIN OF c_job_status,
      created   TYPE char12 VALUE 'CREATED',
      running   TYPE char12 VALUE 'RUNNING',
      success   TYPE char12 VALUE 'SUCCESS',
      partial   TYPE char12 VALUE 'PARTIAL',
      no_work   TYPE char12 VALUE 'NO_WORK',
      failed    TYPE char12 VALUE 'FAILED',
      cancelled TYPE char12 VALUE 'CANCELLED',
      dry_run   TYPE char12 VALUE 'DRY_RUN',
    END OF c_job_status.

  CONSTANTS:
    BEGIN OF c_trigger_type,
      scheduled TYPE char12 VALUE 'SCHEDULED',
      manual    TYPE char12 VALUE 'MANUAL',
      system    TYPE char12 VALUE 'SYSTEM',
      recovery  TYPE char12 VALUE 'RECOVERY',
      test      TYPE char12 VALUE 'TEST',
    END OF c_trigger_type.

  CONSTANTS:
    BEGIN OF c_failure_mode,
      fail_fast    TYPE char20 VALUE 'FAIL_FAST',
      continue_run TYPE char20 VALUE 'CONTINUE',
    END OF c_failure_mode.

  CONSTANTS:
    BEGIN OF c_selection_mode,
      closed_recon    TYPE char20 VALUE 'CLOSED_RECON',
      frozen_recon    TYPE char20 VALUE 'FROZEN_RECON',
      posting_pointer TYPE char20 VALUE 'POSTING_POINTER',
      explicit_scope  TYPE char20 VALUE 'EXPLICIT_SCOPE',
    END OF c_selection_mode.

  CONSTANTS:
    BEGIN OF c_retention_mode,
      dry_run          TYPE char20 VALUE 'DRY_RUN',
      report_only      TYPE char20 VALUE 'REPORT_ONLY',
      approved_execute TYPE char20 VALUE 'APPROVED_EXECUTE',
    END OF c_retention_mode.

  TYPES: BEGIN OF ty_job_parameter,
           name  TYPE char40,
           value TYPE char120,
         END OF ty_job_parameter.
  TYPES tt_job_parameter TYPE STANDARD TABLE OF ty_job_parameter WITH EMPTY KEY.

  TYPES: BEGIN OF ty_job_context,
           jobrun_id              TYPE /fcbp/if_glt_types=>ty_jobrun_id,
           job_name               TYPE char40,
           job_type               TYPE char30,
           trigger_type           TYPE char12,
           actor_id               TYPE char40,
           correlation_id         TYPE /fcbp/if_glt_types=>ty_correlation_id,
           target_id              TYPE char20,
           source_system          TYPE char30,
           source_type            TYPE char20,
           source_reference       TYPE char50,
           source_doc_no          TYPE char20,
           reconciliation_key     TYPE char32,
           event_type             TYPE char30,
           event_id               TYPE char50,
           company_code           TYPE char4,
           ledger_group           TYPE char10,
           fiscal_year            TYPE numc4,
           posting_period         TYPE numc3,
           date_from              TYPE dats,
           date_to                TYPE dats,
           transfer_id            TYPE /fcbp/if_glt_types=>ty_transfer_id,
           package_id             TYPE char32,
           outbox_id              TYPE /fcbp/if_glt_types=>ty_outbox_id,
           policy_context_id      TYPE char32,
           work_type              TYPE char20,
           retry_type             TYPE char20,
           processing_mode        TYPE char10,
           due_before             TYPE utclong,
           max_items              TYPE i,
           max_scopes             TYPE i,
           max_runtime_seconds    TYPE i,
           max_attempts           TYPE i,
           priority_max           TYPE i,
           fail_fast              TYPE abap_bool,
           dry_run                TYPE abap_bool,
           immediate_dispatch     TYPE abap_bool,
           reason_code            TYPE char30,
           approval_reference     TYPE char80,
           selection_mode         TYPE char20,
           retention_mode         TYPE char20,
           action_mode            TYPE char20,
           health_mode            TYPE char20,
           persist_findings       TYPE abap_bool,
           rule_profile           TYPE char40,
           mapping_profile        TYPE char40,
           policy_family          TYPE char30,
           execution_context_hash TYPE char64,
         END OF ty_job_context.

  TYPES: BEGIN OF ty_dispatch_context,
           jobrun_id           TYPE /fcbp/if_glt_types=>ty_jobrun_id,
           claim_owner         TYPE char40,
           target_id           TYPE char20,
           work_type           TYPE char20,
           processing_mode     TYPE char10,
           due_before          TYPE utclong,
           max_items           TYPE i,
           max_runtime_seconds TYPE i,
           priority_max        TYPE i,
           dry_run             TYPE abap_bool,
           actor_id            TYPE char40,
           correlation_id      TYPE /fcbp/if_glt_types=>ty_correlation_id,
         END OF ty_dispatch_context.

  TYPES: BEGIN OF ty_job_result,
           jobrun_id          TYPE /fcbp/if_glt_types=>ty_jobrun_id,
           status_code        TYPE char12,
           selected_count     TYPE i,
           claimed_count      TYPE i,
           processed_count    TYPE i,
           success_count      TYPE i,
           failed_count       TYPE i,
           skipped_count      TYPE i,
           duplicate_count    TYPE i,
           registered_count   TYPE i,
           rescheduled_count  TYPE i,
           no_work_count      TYPE i,
           warning_count      TYPE i,
           error_count        TYPE i,
           dry_run_count      TYPE i,
           message_text       TYPE char220,
           app_log_ref        TYPE char80,
           audit_event_id     TYPE /fcbp/if_glt_types=>ty_audit_id,
           retryable          TYPE abap_bool,
         END OF ty_job_result.

  TYPES: BEGIN OF ty_source_selection_request,
           source_system   TYPE char30,
           source_type     TYPE char20,
           company_code    TYPE char4,
           fiscal_year     TYPE numc4,
           posting_period  TYPE numc3,
           date_from       TYPE dats,
           date_to         TYPE dats,
           target_id       TYPE char20,
           selection_mode  TYPE char20,
           max_scopes      TYPE i,
           dry_run         TYPE abap_bool,
           actor_id        TYPE char40,
           correlation_id  TYPE /fcbp/if_glt_types=>ty_correlation_id,
         END OF ty_source_selection_request.

  TYPES: BEGIN OF ty_source_candidate,
           source_system        TYPE char30,
           source_type          TYPE char20,
           source_reference     TYPE char50,
           source_doc_no        TYPE char20,
           reconciliation_key   TYPE char32,
           event_type           TYPE char30,
           event_id             TYPE char50,
           company_code         TYPE char4,
           ledger_group         TYPE char10,
           fiscal_year          TYPE numc4,
           posting_period       TYPE numc3,
           target_id            TYPE char20,
           source_object_key    TYPE char80,
           idempotency_key      TYPE /fcbp/if_glt_types=>ty_idempotency_key,
           processing_mode      TYPE char10,
           requested_by         TYPE char40,
           source_payload_hash  TYPE char64,
           routing_hint         TYPE char40,
           external_corr_id     TYPE char80,
         END OF ty_source_candidate.
  TYPES tt_source_candidate TYPE STANDARD TABLE OF ty_source_candidate WITH EMPTY KEY.

ENDINTERFACE.
