"! Adapter Layer DTOs, capability matrix, and protocol-normalization constants.
INTERFACE /fcbp/if_glt_adapter_types PUBLIC.

  CONSTANTS:
    BEGIN OF c_adapter_type,
      mock              TYPE char30 VALUE 'MOCK',
      mock_adapter      TYPE char30 VALUE 'MOCK_ADAPTER',
      s4_public_cloud   TYPE char30 VALUE 'S4_PUBLIC_CLOUD',
      s4_private_cloud  TYPE char30 VALUE 'S4_PRIVATE_CLOUD',
      integration_suite TYPE char30 VALUE 'INTEGRATION_SUITE',
      cpi               TYPE char30 VALUE 'CPI',
      on_premise        TYPE char30 VALUE 'ON_PREMISE',
    END OF c_adapter_type.

  CONSTANTS:
    BEGIN OF c_protocol_category,
      http        TYPE char30 VALUE 'HTTP',
      odata       TYPE char30 VALUE 'ODATA',
      soap        TYPE char30 VALUE 'SOAP',
      rfc         TYPE char30 VALUE 'RFC',
      middleware  TYPE char30 VALUE 'MIDDLEWARE',
      timeout     TYPE char30 VALUE 'TIMEOUT',
      parser      TYPE char30 VALUE 'PARSER',
      config      TYPE char30 VALUE 'CONFIG',
      internal    TYPE char30 VALUE 'INTERNAL',
      mock        TYPE char30 VALUE 'MOCK',
    END OF c_protocol_category.

  CONSTANTS:
    BEGIN OF c_mock_scenario,
      posted              TYPE char30 VALUE 'POSTED',
      retryable_failure   TYPE char30 VALUE 'RETRYABLE_FAILURE',
      final_failure       TYPE char30 VALUE 'FINAL_FAILURE',
      unknown_confirmation TYPE char30 VALUE 'UNKNOWN_CONFIRMATION',
      pending             TYPE char30 VALUE 'PENDING',
      not_found           TYPE char30 VALUE 'NOT_FOUND',
      timeout_after_send  TYPE char30 VALUE 'TIMEOUT_AFTER_SEND',
      timeout_before_send TYPE char30 VALUE 'TIMEOUT_BEFORE_SEND',
    END OF c_mock_scenario.

  CONSTANTS:
    BEGIN OF c_query_handle_type,
      target_document      TYPE char30 VALUE 'TARGET_DOCUMENT',
      target_correlation   TYPE char30 VALUE 'TARGET_CORRELATION',
      middleware_message   TYPE char30 VALUE 'MIDDLEWARE_MESSAGE',
      bridge_correlation   TYPE char30 VALUE 'BRIDGE_CORRELATION',
      idempotency_key      TYPE char30 VALUE 'IDEMPOTENCY_KEY',
      response_reference   TYPE char30 VALUE 'RESPONSE_REFERENCE',
    END OF c_query_handle_type.

  CONSTANTS:
    BEGIN OF c_idempotency_status,
      not_supported TYPE char30 VALUE 'NOT_SUPPORTED',
      sent          TYPE char30 VALUE 'SENT',
      accepted      TYPE char30 VALUE 'ACCEPTED',
      duplicate     TYPE char30 VALUE 'DUPLICATE',
      unknown       TYPE char30 VALUE 'UNKNOWN',
    END OF c_idempotency_status.

  TYPES: BEGIN OF ty_timeout_policy,
           submit_timeout_sec TYPE i,
           query_timeout_sec  TYPE i,
           poll_interval_sec  TYPE i,
           max_poll_sec       TYPE i,
         END OF ty_timeout_policy.

  TYPES: BEGIN OF ty_status_handles,
           target_doc_no         TYPE char30,
           target_company_code   TYPE char4,
           target_fiscal_year    TYPE numc4,
           target_correlation_id TYPE /fcbp/if_glt_types=>ty_correlation_id,
           middleware_message_id TYPE char80,
           bridge_correlation_id TYPE /fcbp/if_glt_types=>ty_correlation_id,
           idempotency_key       TYPE /fcbp/if_glt_types=>ty_idempotency_key,
           prior_response_ref    TYPE char255,
           raw_ref_hash          TYPE char64,
         END OF ty_status_handles.

  TYPES: BEGIN OF ty_capability,
           adapter_type              TYPE char30,
           target_type               TYPE char20,
           supports_submit           TYPE abap_bool,
           supports_status_query     TYPE abap_bool,
           supports_idempotency_key  TYPE abap_bool,
           supports_correlation_id   TYPE abap_bool,
           supports_sync_confirm     TYPE abap_bool,
           supports_async_confirm    TYPE abap_bool,
           supports_export_only      TYPE abap_bool,
           supports_cancel           TYPE abap_bool,
           max_lines                 TYPE i,
           max_payload_size          TYPE i,
           rate_limit                TYPE i,
           max_parallel              TYPE i,
           productive_allowed        TYPE abap_bool,
           matrix_complete           TYPE abap_bool,
           status_handle_types       TYPE char120,
           notes                     TYPE char220,
         END OF ty_capability.
  TYPES tt_capability TYPE STANDARD TABLE OF ty_capability WITH EMPTY KEY.

  TYPES: BEGIN OF ty_submit_request,
           transfer_id        TYPE /fcbp/if_glt_types=>ty_transfer_id,
           package_id         TYPE char32,
           outdoc_id          TYPE char32,
           policy_context_id  TYPE /fcbp/if_glt_config_types=>ty_policy_context_id,
           target_id          TYPE char20,
           target_type        TYPE char20,
           target_system      TYPE char30,
           target_adapter     TYPE char30,
           destination_alias  TYPE char40,
           confirmation_mode  TYPE char20,
           correlation_id     TYPE /fcbp/if_glt_types=>ty_correlation_id,
           idempotency_key    TYPE /fcbp/if_glt_types=>ty_idempotency_key,
           request_hash       TYPE /fcbp/if_glt_types=>ty_request_hash,
           journal_hash       TYPE char64,
           raw_request_ref    TYPE char255,
           mock_scenario      TYPE char30,
           timeout_policy     TYPE ty_timeout_policy,
           capability         TYPE ty_capability,
         END OF ty_submit_request.

  TYPES: BEGIN OF ty_query_request,
           transfer_id        TYPE /fcbp/if_glt_types=>ty_transfer_id,
           package_id         TYPE char32,
           outdoc_id          TYPE char32,
           policy_context_id  TYPE /fcbp/if_glt_config_types=>ty_policy_context_id,
           target_id          TYPE char20,
           target_type        TYPE char20,
           target_system      TYPE char30,
           target_adapter     TYPE char30,
           destination_alias  TYPE char40,
           confirmation_mode  TYPE char20,
           correlation_id     TYPE /fcbp/if_glt_types=>ty_correlation_id,
           idempotency_key    TYPE /fcbp/if_glt_types=>ty_idempotency_key,
           status_handles     TYPE ty_status_handles,
           query_handle_type  TYPE char30,
           mock_scenario      TYPE char30,
           timeout_policy     TYPE ty_timeout_policy,
           capability         TYPE ty_capability,
         END OF ty_query_request.

  TYPES: BEGIN OF ty_payload,
           payload_hash     TYPE char64,
           raw_payload_ref  TYPE char255,
           content_type     TYPE char80,
           header_names     TYPE char255,
           body_ref         TYPE char255,
           contains_payload TYPE abap_bool,
         END OF ty_payload.

  TYPES: BEGIN OF ty_protocol_response,
           operation               TYPE char20,
           protocol_category       TYPE char30,
           http_status             TYPE i,
           target_message_code     TYPE char40,
           target_message_text_safe TYPE char220,
           middleware_message_id   TYPE char80,
           target_correlation_id   TYPE /fcbp/if_glt_types=>ty_correlation_id,
           target_doc_no           TYPE char30,
           target_company_code     TYPE char4,
           target_fiscal_year      TYPE numc4,
           response_hash           TYPE char64,
           raw_response_ref        TYPE char255,
           timeout_occurred        TYPE abap_bool,
           may_have_been_sent      TYPE abap_bool,
           retryable_safe          TYPE abap_bool,
           business_rejection      TYPE abap_bool,
           accepted_pending        TYPE abap_bool,
           not_found               TYPE abap_bool,
           confirmed               TYPE abap_bool,
           duplicate_replay        TYPE abap_bool,
           idempotency_status      TYPE char30,
           query_handle_type       TYPE char30,
         END OF ty_protocol_response.

  TYPES: BEGIN OF ty_connection_result,
           target_id         TYPE char20,
           target_adapter    TYPE char30,
           destination_alias TYPE char40,
           reachable         TYPE abap_bool,
           health_state      TYPE char12,
           blocking          TYPE abap_bool,
           finding_code      TYPE char40,
           operator_text     TYPE char220,
           checked_at        TYPE utclong,
           capability        TYPE ty_capability,
         END OF ty_connection_result.

ENDINTERFACE.
