"! Configuration Layer DTOs and constants for target profiles, policy families, and policy-context evidence.
INTERFACE /fcbp/if_glt_config_types PUBLIC.

  CONSTANTS:
    BEGIN OF c_lifecycle_state,
      draft          TYPE char20 VALUE 'DRAFT',
      inactive       TYPE char20 VALUE 'INACTIVE',
      pending_health TYPE char20 VALUE 'PENDING_HEALTH',
      health_failed  TYPE char20 VALUE 'HEALTH_FAILED',
      active         TYPE char20 VALUE 'ACTIVE',
      blocked        TYPE char20 VALUE 'BLOCKED',
      superseded     TYPE char20 VALUE 'SUPERSEDED',
      expired        TYPE char20 VALUE 'EXPIRED',
      deactivated    TYPE char20 VALUE 'DEACTIVATED',
    END OF c_lifecycle_state.

  CONSTANTS:
    BEGIN OF c_health_state,
      ok      TYPE char12 VALUE 'OK',
      warning TYPE char12 VALUE 'WARNING',
      blocked TYPE char12 VALUE 'BLOCKED',
      unknown TYPE char12 VALUE 'UNKNOWN',
    END OF c_health_state.

  CONSTANTS:
    BEGIN OF c_target_type,
      s4_public_cloud  TYPE char20 VALUE 'S4_PUBLIC_CLOUD',
      s4_private_cloud TYPE char20 VALUE 'S4_PRIVATE_CLOUD',
      integration_suite TYPE char20 VALUE 'INTEGRATION_SUITE',
      on_prem          TYPE char20 VALUE 'ON_PREM',
      mock             TYPE char20 VALUE 'MOCK',
    END OF c_target_type.

  CONSTANTS:
    BEGIN OF c_object_type,
      target_profile      TYPE char30 VALUE 'TARGET_PROFILE',
      retry_policy        TYPE char30 VALUE 'RETRY_POLICY',
      aggregation_policy  TYPE char30 VALUE 'AGGREGATION_POLICY',
      aggregation_field   TYPE char30 VALUE 'AGGREGATION_FIELD',
      split_policy        TYPE char30 VALUE 'SPLIT_POLICY',
      validation_rule     TYPE char30 VALUE 'VALIDATION_RULE',
      mapping_rule        TYPE char30 VALUE 'MAPPING_RULE',
      throttle_policy     TYPE char30 VALUE 'THROTTLE_POLICY',
      confirmation_policy TYPE char30 VALUE 'CONFIRMATION_POLICY',
      policy_context      TYPE char30 VALUE 'POLICY_CONTEXT',
    END OF c_object_type.

  CONSTANTS:
    BEGIN OF c_resolution_reason,
      missing      TYPE char40 VALUE 'CONFIG_MISSING',
      inactive     TYPE char40 VALUE 'CONFIG_INACTIVE',
      expired      TYPE char40 VALUE 'CONFIG_EXPIRED',
      ambiguous    TYPE char40 VALUE 'CONFIG_AMBIGUOUS',
      unsupported  TYPE char40 VALUE 'CONFIG_UNSUPPORTED',
      unhealthy    TYPE char40 VALUE 'CONFIG_UNHEALTHY',
      inconsistent TYPE char40 VALUE 'CONFIG_INCONSISTENT',
      auth         TYPE char40 VALUE 'CONFIG_AUTHORIZATION',
    END OF c_resolution_reason.

  TYPES ty_policy_context_id TYPE char32.
  TYPES ty_health_run_id TYPE char32.

  TYPES: BEGIN OF ty_routing_scope,
           transfer_id       TYPE /fcbp/if_glt_types=>ty_transfer_id,
           transfer_type     TYPE char20,
           source_system     TYPE char30,
           source_type       TYPE char20,
           source_reference  TYPE char50,
           company_code      TYPE char4,
           ledger_group      TYPE char10,
           document_type     TYPE char10,
           processing_mode   TYPE char10,
           routing_hint      TYPE char40,
           resolution_date   TYPE dats,
           resolution_time   TYPE tims,
           requested_by      TYPE char40,
           correlation_id    TYPE /fcbp/if_glt_types=>ty_correlation_id,
         END OF ty_routing_scope.

  TYPES: BEGIN OF ty_target_profile,
           target_id              TYPE char20,
           target_type            TYPE char20,
           adapter_type           TYPE char20,
           destination_alias      TYPE char40,
           transfer_mode          TYPE char10,
           confirmation_mode      TYPE char20,
           retry_policy_id        TYPE char20,
           aggregation_profile_id TYPE char20,
           split_profile_id       TYPE char20,
           validation_profile_id  TYPE char20,
           mapping_policy_id      TYPE char20,
           throttle_policy_id     TYPE char20,
           confirmation_policy_id TYPE char20,
           source_system          TYPE char30,
           source_type            TYPE char20,
           transfer_type          TYPE char20,
           company_code           TYPE char4,
           ledger_group           TYPE char10,
           processing_mode        TYPE char10,
           active_flag            TYPE abap_bool,
           lifecycle_state        TYPE char20,
           valid_from             TYPE dats,
           valid_to               TYPE dats,
           priority               TYPE i,
           health_state           TYPE char12,
           config_version         TYPE i,
           config_hash            TYPE char64,
           created_by             TYPE syuname,
           created_at             TYPE utclong,
           changed_by             TYPE syuname,
           changed_at             TYPE utclong,
           activated_by           TYPE syuname,
           activated_at           TYPE utclong,
         END OF ty_target_profile.
  TYPES tt_target_profile TYPE STANDARD TABLE OF ty_target_profile WITH EMPTY KEY.

  TYPES: BEGIN OF ty_retry_policy,
           retry_policy_id        TYPE char20,
           version                TYPE i,
           active_flag            TYPE abap_bool,
           lifecycle_state        TYPE char20,
           valid_from             TYPE dats,
           valid_to               TYPE dats,
           config_hash            TYPE char64,
           max_attempts           TYPE i,
           retryable_categories   TYPE char120,
           initial_delay_sec      TYPE i,
           max_delay_sec          TYPE i,
           backoff_model          TYPE char20,
           jitter_policy          TYPE char30,
           exhaustion_behavior    TYPE char30,
           poll_before_retry      TYPE abap_bool,
           operator_action_rule   TYPE char30,
           changed_by             TYPE syuname,
           changed_at             TYPE utclong,
         END OF ty_retry_policy.

  TYPES: BEGIN OF ty_aggregation_policy,
           aggregation_profile_id TYPE char20,
           version                TYPE i,
           active_flag            TYPE abap_bool,
           lifecycle_state        TYPE char20,
           config_hash            TYPE char64,
           grouping_mode          TYPE char20,
           required_dimension_policy TYPE char80,
           netting_allowed        TYPE abap_bool,
           source_hash_version    TYPE char20,
           changed_by             TYPE syuname,
           changed_at             TYPE utclong,
         END OF ty_aggregation_policy.

  TYPES: BEGIN OF ty_aggregation_field,
           aggregation_profile_id TYPE char20,
           version                TYPE i,
           field_sequence         TYPE i,
           field_name             TYPE char40,
           required_flag          TYPE abap_bool,
           normalize_rule         TYPE char30,
           include_in_signature   TYPE abap_bool,
           changed_by             TYPE syuname,
           changed_at             TYPE utclong,
         END OF ty_aggregation_field.
  TYPES tt_aggregation_field TYPE STANDARD TABLE OF ty_aggregation_field WITH EMPTY KEY.

  TYPES: BEGIN OF ty_split_policy,
           split_profile_id       TYPE char20,
           version                TYPE i,
           active_flag            TYPE abap_bool,
           lifecycle_state        TYPE char20,
           config_hash            TYPE char64,
           max_lines_per_doc      TYPE i,
           max_amount             TYPE p LENGTH 16 DECIMALS 2,
           split_by_company_code  TYPE abap_bool,
           split_by_currency      TYPE abap_bool,
           split_by_posting_date  TYPE abap_bool,
           split_by_gl_doc_type   TYPE abap_bool,
           split_by_ledger_group  TYPE abap_bool,
           balance_scope          TYPE char30,
           changed_by             TYPE syuname,
           changed_at             TYPE utclong,
         END OF ty_split_policy.

  TYPES: BEGIN OF ty_validation_rule,
           validation_profile_id  TYPE char20,
           rule_id                TYPE char30,
           version                TYPE i,
           active_flag            TYPE abap_bool,
           config_hash            TYPE char64,
           rule_category          TYPE char30,
           severity               TYPE char10,
           blocking_flag          TYPE abap_bool,
           target_scope           TYPE char40,
           field_scope            TYPE char40,
           policy_expression_ref  TYPE char80,
           changed_by             TYPE syuname,
           changed_at             TYPE utclong,
         END OF ty_validation_rule.
  TYPES tt_validation_rule TYPE STANDARD TABLE OF ty_validation_rule WITH EMPTY KEY.

  TYPES: BEGIN OF ty_mapping_rule,
           mapping_policy_id      TYPE char20,
           mapping_rule_id        TYPE char30,
           version                TYPE i,
           active_flag            TYPE abap_bool,
           config_hash            TYPE char64,
           field_name             TYPE char40,
           source_value           TYPE char80,
           source_pattern         TYPE char80,
           target_value           TYPE char80,
           decision_type          TYPE char20,
           derivation_ref         TYPE char80,
           truncation_rule        TYPE char30,
           pass_through_allowed   TYPE abap_bool,
           priority               TYPE i,
           changed_by             TYPE syuname,
           changed_at             TYPE utclong,
         END OF ty_mapping_rule.
  TYPES tt_mapping_rule TYPE STANDARD TABLE OF ty_mapping_rule WITH EMPTY KEY.

  TYPES: BEGIN OF ty_throttle_policy,
           throttle_policy_id     TYPE char20,
           version                TYPE i,
           active_flag            TYPE abap_bool,
           lifecycle_state        TYPE char20,
           config_hash            TYPE char64,
           max_parallel           TYPE i,
           max_per_run            TYPE i,
           rate_limit             TYPE i,
           dispatch_window        TYPE char80,
           retry_backlog_limit    TYPE i,
           poll_backlog_limit     TYPE i,
           changed_by             TYPE syuname,
           changed_at             TYPE utclong,
         END OF ty_throttle_policy.

  TYPES: BEGIN OF ty_confirmation_policy,
           confirmation_policy_id TYPE char20,
           version                TYPE i,
           active_flag            TYPE abap_bool,
           lifecycle_state        TYPE char20,
           config_hash            TYPE char64,
           confirmation_mode      TYPE char20,
           status_query_required  TYPE abap_bool,
           poll_interval_sec      TYPE i,
           max_poll_duration_sec  TYPE i,
           status_handle_type     TYPE char30,
           unknown_behavior       TYPE char30,
           safe_retry_after_negative_query TYPE abap_bool,
           changed_by             TYPE syuname,
           changed_at             TYPE utclong,
         END OF ty_confirmation_policy.

  TYPES: BEGIN OF ty_effective_context,
           routing_scope          TYPE ty_routing_scope,
           target_profile         TYPE ty_target_profile,
           retry_policy           TYPE ty_retry_policy,
           aggregation_policy     TYPE ty_aggregation_policy,
           aggregation_fields     TYPE tt_aggregation_field,
           split_policy           TYPE ty_split_policy,
           validation_rules       TYPE tt_validation_rule,
           mapping_rules          TYPE tt_mapping_rule,
           throttle_policy        TYPE ty_throttle_policy,
           confirmation_policy    TYPE ty_confirmation_policy,
           policy_context_id      TYPE ty_policy_context_id,
           resolved_at            TYPE utclong,
           resolved_by            TYPE syuname,
         END OF ty_effective_context.

  TYPES: BEGIN OF ty_policy_context,
           policy_context_id      TYPE ty_policy_context_id,
           transfer_id            TYPE /fcbp/if_glt_types=>ty_transfer_id,
           package_id             TYPE char32,
           outbox_id              TYPE /fcbp/if_glt_types=>ty_outbox_id,
           target_id              TYPE char20,
           target_profile_version TYPE i,
           target_profile_hash    TYPE char64,
           aggregation_profile_id TYPE char20,
           aggregation_version    TYPE i,
           aggregation_hash       TYPE char64,
           split_profile_id       TYPE char20,
           split_version          TYPE i,
           split_hash             TYPE char64,
           validation_profile_id  TYPE char20,
           validation_version     TYPE i,
           validation_hash        TYPE char64,
           mapping_policy_id      TYPE char20,
           mapping_version        TYPE i,
           mapping_hash           TYPE char64,
           retry_policy_id        TYPE char20,
           retry_version          TYPE i,
           retry_hash             TYPE char64,
           throttle_policy_id     TYPE char20,
           throttle_version       TYPE i,
           throttle_hash          TYPE char64,
           confirmation_policy_id TYPE char20,
           confirmation_version   TYPE i,
           confirmation_hash      TYPE char64,
           resolved_at            TYPE utclong,
           resolved_by            TYPE syuname,
           validity_from          TYPE dats,
           validity_to            TYPE dats,
         END OF ty_policy_context.
  TYPES tt_policy_context TYPE STANDARD TABLE OF ty_policy_context WITH EMPTY KEY.

  TYPES: BEGIN OF ty_health_finding,
           health_run_id          TYPE ty_health_run_id,
           target_id              TYPE char20,
           config_object_type     TYPE char30,
           config_object_key      TYPE char80,
           check_id               TYPE char30,
           severity               TYPE char10,
           blocking_flag          TYPE abap_bool,
           finding_code           TYPE char40,
           operator_text          TYPE char220,
           evidence_ref           TYPE char255,
           checked_at             TYPE utclong,
           checked_by             TYPE syuname,
         END OF ty_health_finding.
  TYPES tt_health_finding TYPE STANDARD TABLE OF ty_health_finding WITH EMPTY KEY.

ENDINTERFACE.
